// Generated by https://quicktype.io

export interface Manager {
    country:                        string;
    identification_number:          string;
    identification_type_code:       string;
    identification_type:            string;
    identification_issue_date:      string;
    identification_expiration_date: string;
    contact_name:                   ContactName;
    birth_date:                     string;
    birth_country_code:             string;
    birth_country:                  string;
    marital_status_code:            string;
    marital_status:                 string;
    nationality_code:               string;
    nationality:                    string;
    profession_code:                string;
    profession:                     string;
    economic_activity_code:         string;
    economic_activity:              string;
    location_information:           LocationInformation;
    job_information:                JobInformation;
    is_pep:                         boolean;
}

export interface ContactName {
    first_name:       string;
    second_name:      string;
    last_name:        string;
    second_last_name: string;
}

export interface JobInformation {
    job_code:               string;
    job:                    string;
    monthly_income:         number;
    work_place:             string;
    work_geo_location_code: string;
    work_geo_location:      string;
}

export interface LocationInformation {
    residence_code:    string;
    residence:         string;
    address:           string;
    geo_location_code: string;
    geo_location:      string;
    phone:             string;
    cell_phone:        string;
    email:             string;
}
